// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mock.go -package=ledger
//

// Package ledger is a generated GoMock package.
package ledger

import (
	context "context"
	reflect "reflect"

	ledger "github.com/clodoaldomarques/ledger-worker/internal/domain/ledger"
	gomock "go.uber.org/mock/gomock"
)

// MockEventsProvider is a mock of EventsProvider interface.
type MockEventsProvider struct {
	ctrl     *gomock.Controller
	recorder *MockEventsProviderMockRecorder
	isgomock struct{}
}

// MockEventsProviderMockRecorder is the mock recorder for MockEventsProvider.
type MockEventsProviderMockRecorder struct {
	mock *MockEventsProvider
}

// NewMockEventsProvider creates a new mock instance.
func NewMockEventsProvider(ctrl *gomock.Controller) *MockEventsProvider {
	mock := &MockEventsProvider{ctrl: ctrl}
	mock.recorder = &MockEventsProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventsProvider) EXPECT() *MockEventsProviderMockRecorder {
	return m.recorder
}

// CreateEvent mocks base method.
func (m *MockEventsProvider) CreateEvent(ctx context.Context, e ledger.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEvent", ctx, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateEvent indicates an expected call of CreateEvent.
func (mr *MockEventsProviderMockRecorder) CreateEvent(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEvent", reflect.TypeOf((*MockEventsProvider)(nil).CreateEvent), ctx, e)
}
